// Auto-generated by process_content.py
// Do not edit manually - regenerate with: python process_content.py

const contentData = {
  files: [
  {
    "key": "01_introduction",
    "filename": "01_introduction.md",
    "title": "01 introduction",
    "type": "markdown",
    "path": "./folder_w_text/01_introduction.md",
    "content": "# Introduction\n\nWelcome to the **Static Content Viewer**!\n\nThis viewer supports:\n\n- **Markdown files** (`.md`) - rendered with full formatting\n- **Text files** (`.txt`) - displayed as plain text\n- **Audio files** (`.mp3`, `.m4a`, `.wav`) - playable from the sidebar\n\n## Features\n\n1. Click on text/markdown files to view their content\n2. Click on audio files to play them\n3. Audio plays independently - you can view other content while listening\n4. Keyboard navigation with arrow keys\n\n## Code Example\n\n```python\ndef hello_world():\n    print(\"Hello, World!\")\n```\n\n## Next Steps\n\nBrowse the sidebar to explore more content!\n"
  },
  {
    "key": "02_getting_started",
    "filename": "02_getting_started.txt",
    "title": "02 getting started",
    "type": "text",
    "path": "./folder_w_text/02_getting_started.txt",
    "content": "Getting Started Guide\n=====================\n\nThis is a plain text file demonstrating the text viewer.\n\nUSAGE:\n------\n1. Run: python process_content.py\n2. Start server: python -m http.server 8000\n3. Open: http://localhost:8000\n\nKEYBOARD SHORTCUTS:\n-------------------\n- Up/Down Arrow: Navigate sidebar\n- Enter: Select current item\n- Space: Play/pause audio (when audio is selected)\n\nFILE ORGANIZATION:\n------------------\n- Place .md, .txt, and audio files in folder_w_text/\n- Run process_content.py to regenerate content_data.js\n- Refresh the browser to see changes\n\nSUPPORTED FORMATS:\n------------------\nText:  .txt, .md\nAudio: .mp3, .m4a, .wav, .ogg, .flac\n\n\nJordan is a Smooth Criminal\nhttps://www.youtube.com/watch?v=7G7PDEbND1s?1:00,2:00,3:00"
  },
  {
    "key": "03_sample_notes",
    "filename": "03_sample_notes.md",
    "title": "03 sample notes",
    "type": "markdown",
    "path": "./folder_w_text/03_sample_notes.md",
    "content": "# Sample Notes\n\n## Meeting Notes - Project Review\n\n### Attendees\n- Alice\n- Bob\n- Charlie\n\n### Discussion Points\n\n1. **Timeline Review**\n   - Phase 1 complete\n   - Phase 2 in progress\n   - Phase 3 scheduled for next month\n\n2. **Technical Updates**\n   - New API endpoints deployed\n   - Performance improvements: 40% faster load times\n   - Bug fixes in authentication module\n\n### Action Items\n\n| Task | Owner | Due Date |\n|------|-------|----------|\n| Update documentation | Alice | Friday |\n| Review PR #123 | Bob | Tomorrow |\n| Deploy to staging | Charlie | EOD |\n\n### Notes\n\n> \"The best code is no code at all.\" - Someone wise\n\nRemember to:\n- [ ] Update the changelog\n- [ ] Notify stakeholders\n- [x] Complete code review\n"
  },
  {
    "key": "birds_chriping",
    "filename": "birds_chriping.mp3",
    "title": "birds chriping",
    "type": "audio",
    "path": "./folder_w_text/birds_chriping.mp3",
    "content": null
  },
  {
    "key": "recording-2026-01-28-01-13-17",
    "filename": "recording-2026-01-28-01-13-17.mp3",
    "title": "recording 2026 01 28 01 13 17",
    "type": "audio",
    "path": "./folder_w_text/recording-2026-01-28-01-13-17.mp3",
    "content": null
  },
  {
    "key": "screenshot_2026-01-24_at_10_18_14_pm",
    "filename": "Screenshot 2026-01-24 at 10.18.14 PM.png",
    "title": "Screenshot 2026 01 24 at 10.18.14 PM",
    "type": "image",
    "path": "./folder_w_text/Screenshot 2026-01-24 at 10.18.14 PM.png",
    "content": null
  },
  {
    "key": "screenshot_2026-01-28_at_11_46_44_pm",
    "filename": "Screenshot 2026-01-28 at 11.46.44 PM.png",
    "title": "Screenshot 2026 01 28 at 11.46.44 PM",
    "type": "image",
    "path": "./folder_w_text/Screenshot 2026-01-28 at 11.46.44 PM.png",
    "content": null
  },
  {
    "key": "screenshot_2026-01-28_at_11_47_21_pm",
    "filename": "Screenshot 2026-01-28 at 11.47.21 PM.png",
    "title": "Screenshot 2026 01 28 at 11.47.21 PM",
    "type": "image",
    "path": "./folder_w_text/Screenshot 2026-01-28 at 11.47.21 PM.png",
    "content": null
  }
],
  youtube_links: [
  {
    "url": "https://www.youtube.com/watch?v=7G7PDEbND1s?1:00",
    "video_id": "7G7PDEbND1s",
    "hint": "Jordan is a Smooth Criminal",
    "source_file": "02_getting_started.txt",
    "times": [
      "2:00",
      "3:00"
    ]
  }
]
};
